#!/bin/bash

PG_DOCKER_NAME='gloss_db_draft'
CHECK_DB_RUNNING=$(docker ps | grep $PG_DOCKER_NAME | wc -l)

JH_PATH='/home/omar/Desktop/projects/jobhunter'

JH_BACK_PATH="$JH_PATH/src/backend/"
JH_BACK_CMD="docker restart gloss_db_draft && mvn spring-boot:run"

JH_FRONT_PATH="$JH_PATH/src/frontend/next/"
JH_FRONT_CMD="bun dev"

function verify_db() {
  if ! [ $CHECK_DB_RUNNING -gt 0 ]; then
    echo "Restarting postgres container $PG_DOCKER_NAME"
    docker restart $PG_DOCKER_NAME
  fi
}

function spawn_term() {
  if test $1 = $JH_BACK_PATH; then verify_db $1; fi
  alacritty --working-directory $1 -e bash -i -c "$2" &
}

spawn_term $JH_FRONT_PATH "$JH_FRONT_CMD"
spawn_term $JH_BACK_PATH "$JH_BACK_CMD"
alacritty -e bash -i -c "chromium --app='http://localhost:3000'" &
