services:
  jh-frontend:
    build:
      target: dev
    environment:
      API_ORIGIN: http://jh-backend:8080
      SCRAP_ORIGIN: http://jh-services:8000
    develop:
      watch:
        - path: ./src/frontend/next/
          action: sync
          target: /app

  jh-backend:
    build:
      target: dev
    environment:
      BACK_PORT: 8080
      SERVICES_ORIGIN: http://jh-services:8000
    develop:
      watch:
        - path: ./src/backend
          action: sync
          target: /app

  jh-services:
    build:
      target: dev
    develop:
      watch:
        - path: ./src/services/combined
          action: sync
          target: /app
