server:
  address: 0.0.0.0
  port: 8080
  # port: ${BACK_PORT}
app-services:
  # scrap-service-url: http://jh-services:8001
  scrap-service-url: ${SERVICES_ORIGIN}
app:
  jwt:
    secret: dev-env-jwt-secret
    expiration:
      ms: 900000
debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://jh-postgresql:5432/mydatabase
    # url: jdbc:postgresql://localhost:5432/mydatabase
    # url: jdbc:postgresql://jh-network:5432/mydatabase
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true;
    show-sql: true
    database: postgresql
  security:
    user:
      name: admin
      password: pass
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    # default-schema: "public"
logging:
  level:
    root: INFO
    com:
      jobhunter:
        backend: TRACE
    org:
      springframework:
        boot:
          autoconfigure: ERROR
