# FROM python:3.12.12-alpine AS base
FROM python:3 AS base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .

RUN python -m pip install --upgrade pip setuptools
RUN pip install --no-cache-dir -r requirements.txt
run playwright install
run playwright install-deps

FROM base AS dev
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY . .
EXPOSE 8000
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000", "--reload"]

FROM base AS prod
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY . .
EXPOSE 8000
CMD ["gunicorn", "--bind=0.0.0.0:8000","wsgi:app"]
