### 

@base = http://localhost:5000


### scrap a job offer from a url

POST {{base}}/scrap/ HTTP/1.1
Content-Type: application/json

{
  "url": "https://www.hellowork.com/fr-fr/emplois/67890369.html"
}


### 

GET {{base}}/test/ HTTP/1.1


### 

GET {{base}}/test/llm/ HTTP/1.1
